services:
  web:
    build: .
    image: store:1.0.0
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - 8000:8000

    depends_on:
      - db

  db:
    image: postgres:17-bookworm
    container_name: db
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=home
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=shop_db