# Generated by Django 5.2 on 2025-06-17 14:51

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, null=True, unique=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=155, null=True, unique=True, verbose_name='Название')),
                ('name_uk', models.CharField(max_length=155, null=True, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=155, null=True, unique=True, verbose_name='SLUG_URL')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибути',
                'db_table': 'attribute',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, null=True, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=155, null=True, unique=True, verbose_name='SLUG_URL')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, null=True, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=155, null=True, unique=True, verbose_name='SLUG_URL')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Максимум 4 цифри', max_digits=4, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюти',
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, null=True, verbose_name='Значення')),
                ('value_ru', models.CharField(max_length=50, null=True, verbose_name='Значення')),
                ('value_uk', models.CharField(max_length=50, null=True, verbose_name='Значення')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Значення атрибута',
                'verbose_name_plural': 'Значення атрибутів',
                'db_table': 'attribute_value',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
                ('name_ru', models.CharField(max_length=50, null=True, unique=True, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=50, null=True, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='categories_images/')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, null=True, unique=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=155, null=True, unique=True, verbose_name='Название')),
                ('name_uk', models.CharField(max_length=155, null=True, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=155, null=True, unique=True, verbose_name='SLUG_URL')),
                ('description', models.TextField(null=True, verbose_name='Опис')),
                ('description_ru', models.TextField(null=True, verbose_name='Опис')),
                ('description_uk', models.TextField(null=True, verbose_name='Опис')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Знижка у %')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Категорія')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Зображення')),
                ('article', models.CharField(max_length=255, unique=True, verbose_name='Артикул')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість товару')),
                ('attribute_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attributevalue', verbose_name='Атрибут')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Варіації товару',
                'verbose_name_plural': 'Варіації товару',
                'db_table': 'product_variations',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, null=True, unique=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=155, null=True, unique=True, verbose_name='Название')),
                ('name_uk', models.CharField(max_length=155, null=True, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=155, null=True, unique=True, verbose_name='SLUG_URL')),
                ('value', models.CharField(max_length=50, null=True, verbose_name='Значення')),
                ('value_ru', models.CharField(max_length=50, null=True, verbose_name='Значення')),
                ('value_uk', models.CharField(max_length=50, null=True, verbose_name='Значення')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='product.productvariation', verbose_name='Варіація товару')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'db_table': 'product_characteristics',
            },
        ),
    ]
