# Generated by Django 5.1.4 on 2025-07-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('OUT_OF_STOCK', 'Out Of Stock')], null=True, verbose_name='Статус'),
        ),
    ]
