# Generated by Django 5.1.8 on 2025-05-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productvariation_attribute_attributevalue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'Значение атрибута', 'verbose_name_plural': 'Значения атрибутов'},
        ),
        migrations.AddField(
            model_name='productvariation',
            name='characteristics',
            field=models.JSONField(blank=True, null=True, verbose_name='Характеристики'),
        ),
    ]
