# Generated by Django 5.1.8 on 2025-05-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_attributes',
        ),
    ]
