# Generated by Django 5.1.8 on 2025-05-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_jsondocument_remove_product_product_attributes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='jsondocument',
            name='content',
            field=models.JSONField(verbose_name='Атрибуты'),
        ),
        migrations.AlterField(
            model_name='jsondocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Товар'),
        ),
    ]
