# Generated by Django 5.1.4 on 2025-07-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_status_productvariation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'В наличии'), ('OUT_OF_STOCK', 'Нету в наличии')], null=True, verbose_name='Статус'),
        ),
    ]
