# Generated by Django 5.1.8 on 2025-05-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(max_length=155, null=True, unique=True, verbose_name='SLUG_URL'),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=155, null=True, unique=True, verbose_name='SLUG_URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Без названия', max_length=155, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Без названия', max_length=155, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=155, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=155, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=155, null=True, unique=True, verbose_name='SLUG_URL'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=155, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(max_length=155, null=True, unique=True, verbose_name='SLUG_URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=155, null=True, unique=True, verbose_name='SLUG_URL'),
        ),
    ]
