# Generated by Django 5.1.8 on 2025-05-06 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_testmodel_product_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название атрибута')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
                'db_table': 'attribute',
            },
        ),
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='SLUG_URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='SLUG_URL'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.color'),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибута',
                'db_table': 'attribute_value',
            },
        ),
        migrations.AddField(
            model_name='productvariation',
            name='attribute_values',
            field=models.ManyToManyField(to='product.attributevalue', verbose_name='Значения атрибутов'),
        ),
    ]
