# Generated by Django 5.1.8 on 2025-05-23 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_image_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=155, null=True, unique=True, verbose_name='SLUG_URL')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Курс')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand', verbose_name='Бренд'),
        ),
    ]
