# Generated by Django 5.1.8 on 2025-05-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_attribute_alter_color_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='attribute_values',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
    ]
