# Generated by Django 5.2 on 2025-04-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_color_remove_productitems_name_productitems_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.product'),
        ),
    ]
