# Generated by Django 5.1.8 on 2025-05-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_currency_alter_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelTable(
            name='currency',
            table='currency',
        ),
    ]
