# Generated by Django 5.1.4 on 2025-07-19 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='review',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамілія'),
        ),
        migrations.AlterField(
            model_name='review',
            name='advantages',
            field=models.CharField(blank=True, max_length=255, verbose_name='Переваги'),
        ),
        migrations.AlterField(
            model_name='review',
            name='disadvantages',
            field=models.CharField(blank=True, max_length=255, verbose_name='Недоліки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.productvariation', verbose_name='Варіація продукта'),
        ),
    ]
