# Generated by Django 5.2 on 2025-04-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productitems_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductItems',
            new_name='ProductVariation',
        ),
    ]
