# Generated by Django 5.1.8 on 2025-05-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
