# Generated by Django 5.1.4 on 2025-07-22 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_review_first_name_review_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='in_home_page',
            field=models.BooleanField(null=True, verbose_name='На головній сторінці?'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_home_page',
            field=models.BooleanField(null=True, verbose_name='На головній сторінці?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамілія'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5, message='Максимальна оцінка 5')], verbose_name='Рейтинг'),
        ),
    ]
