# Generated by Django 5.1.8 on 2025-05-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_attribute_productvariation_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='attribute_value',
            field=models.CharField(max_length=50, null=True, verbose_name='Значение атрибута'),
        ),
    ]
