# Generated by Django 5.2 on 2025-05-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_currency_alter_currency_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюти'},
        ),
        migrations.AddField(
            model_name='productvariation',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Знижка у %'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Максимум 4 цифри', max_digits=4, verbose_name='Курс'),
        ),
    ]
