# Generated by Django 5.1.4 on 2025-07-22 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_in_home_page_product_in_home_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='in_home_page',
            field=models.BooleanField(default=False, null=True, verbose_name='На головній сторінці?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_home_page',
            field=models.BooleanField(default=False, null=True, verbose_name='На головній сторінці?'),
        ),
        migrations.CreateModel(
            name='InStockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамілія')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Сповіщено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariation', verbose_name='Варіація товару')),
            ],
            options={
                'verbose_name': 'Товар',
                'db_table': 'in_stock_notification',
            },
        ),
    ]
