# Generated by Django 5.2 on 2025-04-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productvariation_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name': 'Вариации товара'},
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(unique=True, verbose_name='Цвет'),
        ),
        migrations.AlterModelTable(
            name='productvariation',
            table='product_variations',
        ),
    ]
