# Generated by Django 5.2 on 2025-05-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_currency_options_productvariation_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Знижка у %'),
        ),
    ]
