# Generated by Django 5.1.8 on 2025-05-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_brand_delete_jsondocument_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
    ]
