# Generated by Django 5.1.4 on 2025-07-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_in_home_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instocknotification',
            options={'verbose_name': 'Запит на наявність', 'verbose_name_plural': 'Запити на наявність'},
        ),
    ]
