# Generated by Django 5.1.4 on 2025-08-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_instocknotification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='in_home_page',
            field=models.BooleanField(default=False, verbose_name='На головній сторінці?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_home_page',
            field=models.BooleanField(default=False, verbose_name='На головній сторінці?'),
        ),
    ]
