# Generated by Django 5.1.4 on 2025-08-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_category_in_home_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcharacteristics',
            name='slug',
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='name',
            field=models.CharField(max_length=155, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='name_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='name_uk',
            field=models.CharField(max_length=155, null=True, verbose_name='Название'),
        ),
    ]
