# Generated by Django 5.1.4 on 2025-08-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_productcharacteristics_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='slug',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='SLUG_URL'),
        ),
    ]
