# Generated by Django 5.1.4 on 2025-08-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_attributevalue_attribute'),
        ('product', '0013_remove_currency_slug_alter_attribute_name_and_more'),
    ]

    operations = [
    ]
