# Generated by Django 5.1.4 on 2025-07-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=155, unique=True, verbose_name='Слаг')),
                ('content', models.TextField(verbose_name='Контент сторінки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Сторінка',
                'verbose_name_plural': 'Сторінки',
                'db_table': 'page',
            },
        ),
    ]
