# Generated by Django 5.1.4 on 2025-07-24 19:01

# import django_ckeditor_5.fields
#
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(verbose_name='Контент сторінки'),
        ),
    ]
