# Generated by Django 5.1.4 on 2025-07-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_group_alter_page_slug_alter_page_title_page_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткий опис')),
                ('image', models.ImageField(unique=True, upload_to='slides', verbose_name='Зображення')),
                ('is_active', models.BooleanField(verbose_name='Активне?')),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдери',
                'db_table': 'slider',
                'ordering': ['-order'],
            },
        ),
    ]
