# Generated by Django 5.1.4 on 2025-07-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url_text',
            field=models.CharField(default=2, max_length=50, verbose_name='Текст кнопки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(unique=True, upload_to='slides/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(verbose_name='Посилання'),
        ),
    ]
