# Generated by Django 5.1.4 on 2025-08-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slider_url_text_alter_slider_image_alter_slider_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(verbose_name='Контент сторінки'),
        ),
    ]
