# Generated by Django 5.1.4 on 2025-08-02 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('nova_post', 'Нова почта'), ('wayforpay', 'Wayforpay')], max_length=20, verbose_name='Сервіс')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Ключ API',
                'verbose_name_plural': 'Ключі API',
                'db_table': 'api_key',
                'unique_together': {('user', 'service')},
            },
        ),
    ]
