# Generated by Django 5.1.4 on 2025-08-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='created_at',
        ),
    ]
