# Generated by Django 5.2 on 2025-06-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True, verbose_name='Сессия пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariation', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
                'db_table': 'cart',
                'ordering': ('-id',),
            },
        ),
    ]
