# Generated by Django 5.2 on 2025-04-27 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options_alter_cart_product_and_more'),
        ('product', '0008_alter_productvariation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.productvariation'),
            preserve_default=False,
        ),
    ]
