# Generated by Django 5.1.8 on 2025-05-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_quantity'),
        ('product', '0008_remove_product_characteristics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariation'),
        ),
    ]
