# Generated by Django 5.1.8 on 2025-05-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('product', '0003_category_image_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariation', verbose_name='Товар'),
        ),
    ]
