# Generated by Django 5.2 on 2025-04-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='variation',
        ),
    ]
