# Generated by Django 5.2 on 2025-04-28 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_variation'),
        ('product', '0008_alter_productvariation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariation'),
        ),
    ]
