# Generated by Django 5.1.8 on 2025-05-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status', models.CharField(choices=[('PR', 'Обробляється'), ('RC', 'Отримано'), ('AC', 'Прийнято'), ('CL', 'Скасовано'), ('SN', 'Відправлено'), ('SP', 'В дорозі')], default='PR', max_length=2, verbose_name='Статус')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('surname', models.CharField(max_length=30, verbose_name='По батькові')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('warehouse', models.CharField(max_length=255, verbose_name='Відділення НП')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарій')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'db_table': 'order',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
            ],
            options={
                'verbose_name': 'Проданий товар',
                'verbose_name_plural': 'Продані товари',
                'db_table': 'order_item',
            },
        ),
    ]
