# Generated by Django 5.2 on 2025-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('area_description', models.CharField(max_length=50)),
                ('country_type', models.CharField(max_length=36)),
                ('ref', models.CharField(max_length=36)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Населений пункт',
                'verbose_name_plural': 'Населені пункти',
                'db_table': 'countries',
                'ordering': ['country_type'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True, verbose_name='Сессия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status', models.CharField(choices=[('PR', 'Обробляється'), ('RC', 'Отримано'), ('AC', 'Прийнято'), ('CL', 'Скасовано'), ('SN', 'Відправлено'), ('SP', 'В дорозі')], default='PR', max_length=2, verbose_name='Статус')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('surname', models.CharField(max_length=30, verbose_name='По батькові')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('delivery_method', models.CharField(choices=[('PO', 'Поштове відділення'), ('TR', 'Поштомат')], max_length=50, verbose_name='Спосіб доставки')),
                ('country', models.CharField(max_length=100, verbose_name='Місто')),
                ('warehouse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Відділення НП')),
                ('terminal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поштомат НП')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця')),
                ('apartment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Квартира')),
                ('house', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дім')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'db_table': 'order',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
            ],
            options={
                'verbose_name': 'Проданий товар',
                'verbose_name_plural': 'Продані товари',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('warehouse_type', models.CharField(choices=[('PO', 'Поштове відділення'), ('TR', 'Поштомат')], max_length=2)),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Відділення',
                'verbose_name_plural': 'Відділення',
                'db_table': 'warehouses',
                'ordering': ['number'],
            },
        ),
    ]
