# Generated by Django 5.2 on 2025-06-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('PO', 'Поштове відділення'), ('TR', 'Поштомат')], max_length=50, verbose_name='Спосіб доставки'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('PO', 'Поштове відділення'), ('TR', 'Поштомат')], max_length=2),
        ),
    ]
