# Generated by Django 5.2 on 2025-06-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_apartment_remove_order_house_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='warehouse',
            new_name='post_office',
        ),
    ]
