# Generated by Django 5.1.4 on 2025-06-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_delivery_method_and_more'),
        ('order', '0004_rename_warehouse_order_post_office'),
    ]

    operations = [
    ]
