# Generated by Django 5.1.4 on 2025-06-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_merge_20250624_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='do_not_call',
            field=models.BooleanField(default=False, verbose_name='Не передзвонювати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('PO', 'Поштове відділення'), ('TR', 'Поштомат')], default='PO', max_length=50, verbose_name='Спосіб доставки'),
        ),
    ]
