# Generated by Django 5.1.4 on 2025-06-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_do_not_call_alter_order_delivery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.AddField(
            model_name='order',
            name='meest_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто MEEST'),
        ),
        migrations.AddField(
            model_name='order',
            name='meest_warehouse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Відділення Meest'),
        ),
        migrations.AddField(
            model_name='order',
            name='np_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто НП'),
        ),
        migrations.AddField(
            model_name='order',
            name='post_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поштовий індекс'),
        ),
        migrations.AddField(
            model_name='order',
            name='urk_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес УКР'),
        ),
        migrations.AlterField(
            model_name='order',
            name='do_not_call',
            field=models.BooleanField(default=False, verbose_name='Не передзвонювати для підтвердження замовлення'),
        ),
    ]
