# Generated by Django 5.1.4 on 2025-06-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_country_order_meest_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='terminal',
            new_name='np_terminal',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='post_office',
            new_name='np_warehouse',
        ),
        migrations.RemoveField(
            model_name='order',
            name='post_code',
        ),
        migrations.AddField(
            model_name='order',
            name='urk_post_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поштовий індекс УКР'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('NP_WH', 'Поштове відділення Нової почти'), ('NP_TR', 'Поштомат Нової почти'), ('UKR_WH', 'Поштове відділення УКР почти'), ('MEEST_WH', 'Поштове відділення Meest')], default='NP_WH', max_length=50, verbose_name='Спосіб доставки'),
        ),
    ]
