# Generated by Django 5.1.4 on 2025-06-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_terminal_order_np_terminal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='urk_address',
            new_name='ukr_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='urk_post_code',
            new_name='ukr_post_code',
        ),
    ]
