# Generated by Django 5.1.4 on 2025-07-08 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_urk_address_order_ukr_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('NP_WH', 'Відділення Нової пошти'), ('NP_TR', 'Поштомат Нової пошти'), ('UKR_WH', 'Відділення Укрпошти'), ('MEEST_WH', 'Відділення Meest')], default='NP_WH', max_length=50, verbose_name='Спосіб доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=25, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ukr_post_code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)], verbose_name='Поштовий індекс УКР'),
        ),
    ]
