# Generated by Django 5.1.4 on 2025-07-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_delivery_method_alter_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
