# Generated by Django 5.1.4 on 2025-07-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_country_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['warehouse_type'], name='warehouses_warehou_41ce1e_idx'),
        ),
    ]
