# Generated by Django 5.1.4 on 2025-07-24 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_warehouse_warehouses_warehou_41ce1e_idx'),
        ('product', '0010_alter_instocknotification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.productvariation', verbose_name='Варіація товара'),
        ),
    ]
