# Generated by Django 5.1.4 on 2025-08-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(max_length=6, null=True, verbose_name='Номер замовлення'),
        ),
    ]
