# Generated by Django 5.1.4 on 2025-08-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_merge_20250624_0006'),
        ('order', '0016_alter_order_reference'),
    ]

    operations = [
    ]
