# Generated by Django 5.1.4 on 2025-08-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_with_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Ціна на момент покупки'),
        ),
    ]
