# Generated by Django 5.1.4 on 2025-08-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_orderitem_price_with_discount'),
        ('product', '0011_alter_category_in_home_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_variations', to='product.productvariation', verbose_name='Варіація товара'),
        ),
    ]
